spring:
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/keiba
    username: ji-no
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
server:
  port: 8081
logging:
  level:
    org:
      springframework: WARN
mybatis:
  configLocation: classpath:/mybatis/mybatis-config.xml

